CC = gcc

all:golSerial ../SerialToVertical/ConvertVert

golSerial: golSer.c
	$(CC) -o golSerial golSer.c

../SerialToVertical/ConvertVert: ../SerialToVertical/ConvertVert.c
	$(CC) -o ../SerialToVertical/ConvertVert ../SerialToVertical/ConvertVert.c

 
